# Generated by Django 3.0.8 on 2020-09-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('priority', models.PositiveIntegerField()),
                ('expiration_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('age', models.PositiveIntegerField()),
                ('about', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
            ],
        ),
    ]
